### PR TITLE
Lecture 24: Integrative Paradigms of GM: Regularized Bayesian Methods

### PR DESCRIPTION
**Pull request by wngzhiqi**

### CODE REVIEW

**Comment by xunzheng** [comment]
Hi, could you attach a link to the rendered scribe note? I didn't find one. Thanks a lot!

**Comment by wngzhiqi** [comment]
> Hi, could you attach a link to the rendered scribe note? I didn't find one. Thanks a lot!

https://github.com/wngzhiqi/pgm-spring-2019/blob/master/_posts/2019-04-15-lecture-24.md

**Comment by xunzheng** [comment]
> > Hi, could you attach a link to the rendered scribe note? I didn't find one. Thanks a lot!
> 
> https://github.com/wngzhiqi/pgm-spring-2019/blob/master/_posts/2019-04-15-lecture-24.md

Sorry about the confusion. I meant the rendered website link rather than the raw markdown file. It would be easier to check equations before we accept the pull request. Please see e.g. https://github.com/sailinglab/pgm-spring-2019/pull/22

**Comment by wngzhiqi** [comment]
> > > Hi, could you attach a link to the rendered scribe note? I didn't find one. Thanks a lot!
> > 
> > 
> > https://github.com/wngzhiqi/pgm-spring-2019/blob/master/_posts/2019-04-15-lecture-24.md
> 
> Sorry about the confusion. I meant the rendered website link rather than the raw markdown file. It would be easier to check equations before we accept the pull request. Please see e.g. #22

Sorry for the misunderstanding.
The rendered link is here:
https://wngzhiqi.github.io/pgm-spring-2019/notes/lecture-24/

**Comment by alshedivat** [comment]
@xunzheng, can please you review this set of notes ASAP? Thanks.

**Pull request merged**
